# This is a basic workflow to help you get started with Actions

name: vscode

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ vscdoe ]
  pull_request:
    branches: [ vscode ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: mkdir dir dist
        run: |
          mkdir -p ~/dist
      - uses: actions/checkout@v2
      - name: Cache dir
        uses: actions/cache@v2
        with:
          path: ~/dist
          key: ${{ runner.OS }}-${{ hashFiles('~/dist/VSCode-win32-x64-1.53.2.zip') }}
          # restore-keys: |
          #   ${{ runner.OS }}-VSCode-win32-x64
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell      
          
      - name: get vscode
        run: |
          echo get vscode from https://az764295.vo.msecnd.net/stable/622cb03f7e070a9670c94bae1a45d78d7181fbd4/VSCode-win32-x64-1.53.2.zip
          wget https://az764295.vo.msecnd.net/stable/622cb03f7e070a9670c94bae1a45d78d7181fbd4/VSCode-win32-x64-1.53.2.zip
          cp VSCode-win32-x64-1.53.2.zip ~/dist/
          echo ok done.
