# This is a basic workflow to help you get started with Actions

name: prepareEnv

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Cache prepares env
        id: cache-prepares-env
        uses: actions/cache@v2
        with:
          path: ffmpeg-4.3.1.tar.xz
          key: ${{ runner.os }}-ffmpeg-4.3.1

      - name: Cache prepares env2
        id: cache-prepares-env2
        uses: actions/cache@v2
        with:
          path: VSCode-win32-x64-1.53.2.zip
          key: ${{ runner.os }}-VSCode-win32-x64-1.53.2.zip

      # Runs a set of commands using the runners shell
      - name: Run get ffmpeg source
        run: |
          echo http://ffmpeg.org/releases/ffmpeg-4.3.1.tar.xz
          wget http://ffmpeg.org/releases/ffmpeg-4.3.1.tar.xz
          tar xvf ffmpeg-4.3.1.tar.xz
          cd ffmpeg-4.3.1
          ./configure && make
          cd ..
          
      - name: get vscode
        run: |
          echo get vscode from https://az764295.vo.msecnd.net/stable/622cb03f7e070a9670c94bae1a45d78d7181fbd4/VSCode-win32-x64-1.53.2.zip
          wget https://az764295.vo.msecnd.net/stable/622cb03f7e070a9670c94bae1a45d78d7181fbd4/VSCode-win32-x64-1.53.2.zip
          echo ok done.
      
